# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: s3control.aws.upbound.io/v1beta1
kind: AccessGrant
metadata:
  annotations:
    meta.upbound.io/example-id: s3control/v1beta1/accessgrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accessGrantsLocationConfiguration:
    - s3SubPrefix: prefixB*
    accessGrantsLocationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    grantee:
    - granteeIdentifierSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      granteeType: IAM
    permission: READ
    region: us-west-1

---

apiVersion: s3control.aws.upbound.io/v1beta1
kind: AccessGrantsInstance
metadata:
  annotations:
    meta.upbound.io/example-id: s3control/v1beta1/accessgrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1

---

apiVersion: s3control.aws.upbound.io/v1beta1
kind: AccessGrantsLocation
metadata:
  annotations:
    meta.upbound.io/example-id: s3control/v1beta1/accessgrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    iamRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    locationScope: s3://${aws_s3_bucket.example.bucket}/prefixA*
    region: us-west-1
