// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccessGrantInitParameters struct {

	// See Location Configuration below for more details.
	AccessGrantsLocationConfiguration []AccessGrantsLocationConfigurationInitParameters `json:"accessGrantsLocationConfiguration,omitempty" tf:"access_grants_location_configuration,omitempty"`

	// The ID of the S3 Access Grants location to with the access grant is giving access.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/s3control/v1beta1.AccessGrantsLocation
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("access_grants_location_id",true)
	AccessGrantsLocationID *string `json:"accessGrantsLocationId,omitempty" tf:"access_grants_location_id,omitempty"`

	// Reference to a AccessGrantsLocation in s3control to populate accessGrantsLocationId.
	// +kubebuilder:validation:Optional
	AccessGrantsLocationIDRef *v1.NamespacedReference `json:"accessGrantsLocationIdRef,omitempty" tf:"-"`

	// Selector for a AccessGrantsLocation in s3control to populate accessGrantsLocationId.
	// +kubebuilder:validation:Optional
	AccessGrantsLocationIDSelector *v1.NamespacedSelector `json:"accessGrantsLocationIdSelector,omitempty" tf:"-"`

	// The AWS account ID for the S3 Access Grants location.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// See Grantee below for more details.
	Grantee []GranteeInitParameters `json:"grantee,omitempty" tf:"grantee,omitempty"`

	// The access grant's level of access. Valid values: READ, WRITE, READWRITE.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// If you are creating an access grant that grants access to only one object, set this to Object. Valid values: Object.
	S3PrefixType *string `json:"s3PrefixType,omitempty" tf:"s3_prefix_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type AccessGrantObservation struct {

	// Amazon Resource Name (ARN) of the S3 Access Grant.
	AccessGrantArn *string `json:"accessGrantArn,omitempty" tf:"access_grant_arn,omitempty"`

	// Unique ID of the S3 Access Grant.
	AccessGrantID *string `json:"accessGrantId,omitempty" tf:"access_grant_id,omitempty"`

	// See Location Configuration below for more details.
	AccessGrantsLocationConfiguration []AccessGrantsLocationConfigurationObservation `json:"accessGrantsLocationConfiguration,omitempty" tf:"access_grants_location_configuration,omitempty"`

	// The ID of the S3 Access Grants location to with the access grant is giving access.
	AccessGrantsLocationID *string `json:"accessGrantsLocationId,omitempty" tf:"access_grants_location_id,omitempty"`

	// The AWS account ID for the S3 Access Grants location.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The access grant's scope.
	GrantScope *string `json:"grantScope,omitempty" tf:"grant_scope,omitempty"`

	// See Grantee below for more details.
	Grantee []GranteeObservation `json:"grantee,omitempty" tf:"grantee,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The access grant's level of access. Valid values: READ, WRITE, READWRITE.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// If you are creating an access grant that grants access to only one object, set this to Object. Valid values: Object.
	S3PrefixType *string `json:"s3PrefixType,omitempty" tf:"s3_prefix_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type AccessGrantParameters struct {

	// See Location Configuration below for more details.
	// +kubebuilder:validation:Optional
	AccessGrantsLocationConfiguration []AccessGrantsLocationConfigurationParameters `json:"accessGrantsLocationConfiguration,omitempty" tf:"access_grants_location_configuration,omitempty"`

	// The ID of the S3 Access Grants location to with the access grant is giving access.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/s3control/v1beta1.AccessGrantsLocation
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("access_grants_location_id",true)
	// +kubebuilder:validation:Optional
	AccessGrantsLocationID *string `json:"accessGrantsLocationId,omitempty" tf:"access_grants_location_id,omitempty"`

	// Reference to a AccessGrantsLocation in s3control to populate accessGrantsLocationId.
	// +kubebuilder:validation:Optional
	AccessGrantsLocationIDRef *v1.NamespacedReference `json:"accessGrantsLocationIdRef,omitempty" tf:"-"`

	// Selector for a AccessGrantsLocation in s3control to populate accessGrantsLocationId.
	// +kubebuilder:validation:Optional
	AccessGrantsLocationIDSelector *v1.NamespacedSelector `json:"accessGrantsLocationIdSelector,omitempty" tf:"-"`

	// The AWS account ID for the S3 Access Grants location.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// See Grantee below for more details.
	// +kubebuilder:validation:Optional
	Grantee []GranteeParameters `json:"grantee,omitempty" tf:"grantee,omitempty"`

	// The access grant's level of access. Valid values: READ, WRITE, READWRITE.
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// If you are creating an access grant that grants access to only one object, set this to Object. Valid values: Object.
	// +kubebuilder:validation:Optional
	S3PrefixType *string `json:"s3PrefixType,omitempty" tf:"s3_prefix_type,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type AccessGrantsLocationConfigurationInitParameters struct {

	// Sub-prefix.
	S3SubPrefix *string `json:"s3SubPrefix,omitempty" tf:"s3_sub_prefix,omitempty"`
}

type AccessGrantsLocationConfigurationObservation struct {

	// Sub-prefix.
	S3SubPrefix *string `json:"s3SubPrefix,omitempty" tf:"s3_sub_prefix,omitempty"`
}

type AccessGrantsLocationConfigurationParameters struct {

	// Sub-prefix.
	// +kubebuilder:validation:Optional
	S3SubPrefix *string `json:"s3SubPrefix,omitempty" tf:"s3_sub_prefix,omitempty"`
}

type GranteeInitParameters struct {

	// Grantee identifier.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/iam/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	GranteeIdentifier *string `json:"granteeIdentifier,omitempty" tf:"grantee_identifier,omitempty"`

	// Reference to a User in iam to populate granteeIdentifier.
	// +kubebuilder:validation:Optional
	GranteeIdentifierRef *v1.NamespacedReference `json:"granteeIdentifierRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate granteeIdentifier.
	// +kubebuilder:validation:Optional
	GranteeIdentifierSelector *v1.NamespacedSelector `json:"granteeIdentifierSelector,omitempty" tf:"-"`

	// Grantee types. Valid values: DIRECTORY_USER, DIRECTORY_GROUP, IAM.
	GranteeType *string `json:"granteeType,omitempty" tf:"grantee_type,omitempty"`
}

type GranteeObservation struct {

	// Grantee identifier.
	GranteeIdentifier *string `json:"granteeIdentifier,omitempty" tf:"grantee_identifier,omitempty"`

	// Grantee types. Valid values: DIRECTORY_USER, DIRECTORY_GROUP, IAM.
	GranteeType *string `json:"granteeType,omitempty" tf:"grantee_type,omitempty"`
}

type GranteeParameters struct {

	// Grantee identifier.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/iam/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	GranteeIdentifier *string `json:"granteeIdentifier,omitempty" tf:"grantee_identifier,omitempty"`

	// Reference to a User in iam to populate granteeIdentifier.
	// +kubebuilder:validation:Optional
	GranteeIdentifierRef *v1.NamespacedReference `json:"granteeIdentifierRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate granteeIdentifier.
	// +kubebuilder:validation:Optional
	GranteeIdentifierSelector *v1.NamespacedSelector `json:"granteeIdentifierSelector,omitempty" tf:"-"`

	// Grantee types. Valid values: DIRECTORY_USER, DIRECTORY_GROUP, IAM.
	// +kubebuilder:validation:Optional
	GranteeType *string `json:"granteeType" tf:"grantee_type,omitempty"`
}

// AccessGrantSpec defines the desired state of AccessGrant
type AccessGrantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccessGrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessGrantInitParameters `json:"initProvider,omitempty"`
}

// AccessGrantStatus defines the observed state of AccessGrant.
type AccessGrantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessGrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessGrant is the Schema for the AccessGrants API. Provides a resource to manage an S3 Access Grant.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type AccessGrant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permission) || (has(self.initProvider) && has(self.initProvider.permission))",message="spec.forProvider.permission is a required parameter"
	Spec   AccessGrantSpec   `json:"spec"`
	Status AccessGrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessGrantList contains a list of AccessGrants
type AccessGrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessGrant `json:"items"`
}

// Repository type metadata.
var (
	AccessGrant_Kind             = "AccessGrant"
	AccessGrant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessGrant_Kind}.String()
	AccessGrant_KindAPIVersion   = AccessGrant_Kind + "." + CRDGroupVersion.String()
	AccessGrant_GroupVersionKind = CRDGroupVersion.WithKind(AccessGrant_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessGrant{}, &AccessGrantList{})
}
