// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessGrantsLocationInitParameters struct {

	// The AWS account ID for the S3 Access Grants location.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The ARN of the IAM role that S3 Access Grants should use when fulfilling runtime access
	// requests to the location.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/iam/v1beta1.Role
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	IAMRoleArn *string `json:"iamRoleArn,omitempty" tf:"iam_role_arn,omitempty"`

	// Reference to a Role in iam to populate iamRoleArn.
	// +kubebuilder:validation:Optional
	IAMRoleArnRef *v1.Reference `json:"iamRoleArnRef,omitempty" tf:"-"`

	// Selector for a Role in iam to populate iamRoleArn.
	// +kubebuilder:validation:Optional
	IAMRoleArnSelector *v1.Selector `json:"iamRoleArnSelector,omitempty" tf:"-"`

	// The default S3 URI s3:// or the URI to a custom location, a specific bucket or prefix.
	LocationScope *string `json:"locationScope,omitempty" tf:"location_scope,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type AccessGrantsLocationObservation struct {

	// Amazon Resource Name (ARN) of the S3 Access Grants location.
	AccessGrantsLocationArn *string `json:"accessGrantsLocationArn,omitempty" tf:"access_grants_location_arn,omitempty"`

	// Unique ID of the S3 Access Grants location.
	AccessGrantsLocationID *string `json:"accessGrantsLocationId,omitempty" tf:"access_grants_location_id,omitempty"`

	// The AWS account ID for the S3 Access Grants location.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The ARN of the IAM role that S3 Access Grants should use when fulfilling runtime access
	// requests to the location.
	IAMRoleArn *string `json:"iamRoleArn,omitempty" tf:"iam_role_arn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The default S3 URI s3:// or the URI to a custom location, a specific bucket or prefix.
	LocationScope *string `json:"locationScope,omitempty" tf:"location_scope,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type AccessGrantsLocationParameters struct {

	// The AWS account ID for the S3 Access Grants location.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The ARN of the IAM role that S3 Access Grants should use when fulfilling runtime access
	// requests to the location.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/iam/v1beta1.Role
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	IAMRoleArn *string `json:"iamRoleArn,omitempty" tf:"iam_role_arn,omitempty"`

	// Reference to a Role in iam to populate iamRoleArn.
	// +kubebuilder:validation:Optional
	IAMRoleArnRef *v1.Reference `json:"iamRoleArnRef,omitempty" tf:"-"`

	// Selector for a Role in iam to populate iamRoleArn.
	// +kubebuilder:validation:Optional
	IAMRoleArnSelector *v1.Selector `json:"iamRoleArnSelector,omitempty" tf:"-"`

	// The default S3 URI s3:// or the URI to a custom location, a specific bucket or prefix.
	// +kubebuilder:validation:Optional
	LocationScope *string `json:"locationScope,omitempty" tf:"location_scope,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// AccessGrantsLocationSpec defines the desired state of AccessGrantsLocation
type AccessGrantsLocationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccessGrantsLocationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessGrantsLocationInitParameters `json:"initProvider,omitempty"`
}

// AccessGrantsLocationStatus defines the observed state of AccessGrantsLocation.
type AccessGrantsLocationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessGrantsLocationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessGrantsLocation is the Schema for the AccessGrantsLocations API. Provides a resource to manage an S3 Access Grants location.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type AccessGrantsLocation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.locationScope) || (has(self.initProvider) && has(self.initProvider.locationScope))",message="spec.forProvider.locationScope is a required parameter"
	Spec   AccessGrantsLocationSpec   `json:"spec"`
	Status AccessGrantsLocationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessGrantsLocationList contains a list of AccessGrantsLocations
type AccessGrantsLocationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessGrantsLocation `json:"items"`
}

// Repository type metadata.
var (
	AccessGrantsLocation_Kind             = "AccessGrantsLocation"
	AccessGrantsLocation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessGrantsLocation_Kind}.String()
	AccessGrantsLocation_KindAPIVersion   = AccessGrantsLocation_Kind + "." + CRDGroupVersion.String()
	AccessGrantsLocation_GroupVersionKind = CRDGroupVersion.WithKind(AccessGrantsLocation_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessGrantsLocation{}, &AccessGrantsLocationList{})
}
