// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessGrantsInstanceInitParameters struct {

	// The AWS account ID for the S3 Access Grants instance.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The ARN of the AWS IAM Identity Center instance associated with the S3 Access Grants instance.
	IdentityCenterArn *string `json:"identityCenterArn,omitempty" tf:"identity_center_arn,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type AccessGrantsInstanceObservation struct {

	// Amazon Resource Name (ARN) of the S3 Access Grants instance.
	AccessGrantsInstanceArn *string `json:"accessGrantsInstanceArn,omitempty" tf:"access_grants_instance_arn,omitempty"`

	// Unique ID of the S3 Access Grants instance.
	AccessGrantsInstanceID *string `json:"accessGrantsInstanceId,omitempty" tf:"access_grants_instance_id,omitempty"`

	// The AWS account ID for the S3 Access Grants instance.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ARN of the AWS IAM Identity Center instance application; a subresource of the original Identity Center instance.
	IdentityCenterApplicationArn *string `json:"identityCenterApplicationArn,omitempty" tf:"identity_center_application_arn,omitempty"`

	// The ARN of the AWS IAM Identity Center instance associated with the S3 Access Grants instance.
	IdentityCenterArn *string `json:"identityCenterArn,omitempty" tf:"identity_center_arn,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type AccessGrantsInstanceParameters struct {

	// The AWS account ID for the S3 Access Grants instance.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The ARN of the AWS IAM Identity Center instance associated with the S3 Access Grants instance.
	// +kubebuilder:validation:Optional
	IdentityCenterArn *string `json:"identityCenterArn,omitempty" tf:"identity_center_arn,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// AccessGrantsInstanceSpec defines the desired state of AccessGrantsInstance
type AccessGrantsInstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccessGrantsInstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessGrantsInstanceInitParameters `json:"initProvider,omitempty"`
}

// AccessGrantsInstanceStatus defines the observed state of AccessGrantsInstance.
type AccessGrantsInstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessGrantsInstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessGrantsInstance is the Schema for the AccessGrantsInstances API. Provides a resource to manage an S3 Access Grants instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type AccessGrantsInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccessGrantsInstanceSpec   `json:"spec"`
	Status            AccessGrantsInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessGrantsInstanceList contains a list of AccessGrantsInstances
type AccessGrantsInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessGrantsInstance `json:"items"`
}

// Repository type metadata.
var (
	AccessGrantsInstance_Kind             = "AccessGrantsInstance"
	AccessGrantsInstance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessGrantsInstance_Kind}.String()
	AccessGrantsInstance_KindAPIVersion   = AccessGrantsInstance_Kind + "." + CRDGroupVersion.String()
	AccessGrantsInstance_GroupVersionKind = CRDGroupVersion.WithKind(AccessGrantsInstance_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessGrantsInstance{}, &AccessGrantsInstanceList{})
}
