// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *AccessGrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccessGrantsInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccessGrantsInstanceResourcePolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccessGrantsLocation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccessPointPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountPublicAccessBlock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ObjectLambdaAccessPointPolicy) Hub() {}
